apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tnoot39x4-go-gitops
  description: This is GitOps manifest for tnoot39x4-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: tnoot39x4-go
    backstage.io/kubernetes-id: tnoot39x4-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tnoot39x4-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tnoot39x4-go
