apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tnoot39x4-go
  janus-idp.io/tekton: tnoot39x4-go
  backstage.io/kubernetes-id: tnoot39x4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tnoot39x4-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
